site_name: KitOps Manager Documentation

theme:
  name: "material"

plugins: 
  - mkdocstrings

nav:
  - KitOps Manager Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md